app:
  name: 'warehouse-api'
  version: '0.0.1'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'warehouse-api'

postgres:
  pool_max: 2
  url: postgres://admin:password@localhost:5432/warehouse_db