basePath: /v1
definitions:
  v1.reserveRequest:
    properties:
      ids:
        items:
          type: string
        type: array
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
      message: {}
      status:
        type: integer
      status_message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Junior Go Backend test task
  title: Lamoda Warehouses API
  version: "1.0"
paths:
  /reserve:
    delete:
      consumes:
      - application/json
      description: Reserve items in warehouse
      operationId: deleteReservation
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.reserveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Delete Item Reservation
      tags:
      - reservation
    post:
      consumes:
      - application/json
      description: Reserve items in warehouse
      operationId: reserve
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.reserveRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Reserve item
      tags:
      - reservation
swagger: "2.0"
